export const LINKED_LOVELACE_PARTIALS = 'linked-lovelace-partials'
export const LINKED_LOVELACE_TEMPLATE_REPLACEMENT_KEYS_KEY = 'll_keys'
export const LINKED_LOVELACE_TEMPLATE_REPLACEMENT_KEY = 'll_key'
export const LINKED_LOVELACE_TEMPLATE_KEY = 'll_template'
export const LINKED_LOVELACE_TEMPLATE_CONTEXT_KEY = 'll_context'
